server:
  port: 10005
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/,http://peer3:8762/eureka/
spring:
  application:
    name: sso-server
  redis:
    host: 192.168.175.128
    port: 6379
    database: 1
    timeout: 60
    pool:
      max-active: 8
      max-idle: 20
      max-wait: -1
      min-idle: 0
    ## password: